# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Check Terraform Modules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  check-terraform-module:
    name: Check Terraform Module
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v2.3.1
    secrets: inherit
    with:
      working-directory: ./modules
